### ISSUE TITLE
Error while editing server

### ISSUE THREAD

**Issue by Timongcraft** [picapi/MC-ServerSpecificSkins#1]
If you edit a server in the multiplayer menu while the config of the mod is not created (It gets created if you have added a resource pack to a server) But if you have never done that and edit a server the client crashes because it can't find that config file.

**Comment by picapi** [comment]
I'm sorry it's taken so long to respond to this - I've been busy with studies and other matters.
I'll try to fix this issue in the next update which should bring the mod to 1.20.1 - thank you for reporting it!

**Comment by Timongcraft** [comment]
Thanks, it is your time you choose what and when to do things. You don't need to excuse yourself.
